name: stump
description: Stump is a Flutter logger inspired by Timber. It provides a set of static methods to easily log messages and the support to multiple and custom printers.
version: 1.0.1
repository: https://github.com/FedericoMatera/stump

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
